spring:
  application:
    name: CloudGateway
  cloud:
    gateway:
      routes:
        - id: cf-dd-route
          uri: lb://CF-DD
          predicates:
            - Path=/api/v1/**
          filters:
            - RewritePath=/api/v1/(?<segment>.*), /$\{segment}
        - id: cf-designer-route
          uri: lb://CF-Designer-Studio
          predicates:
            - Path=/api/v2/**
          filters:
            - RewritePath=/api/v2/(?<segment>.*), /$\{segment}

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/